#!/bin/bash
# Set colors based on the CATPPUCCIN_FLAVOUR environment variable
case "$CATPPUCCIN_FLAVOUR" in
  "latte")
    # Latte Palette
    export COLOR_ROSEWATER="#dc8a78"
    export COLOR_FLAMINGO="#dd7878"
    export COLOR_PINK="#ea76cb"
    export COLOR_MAUVE="#8839ef"
    export COLOR_RED="#d20f39"
    export COLOR_MAROON="#e64553"
    export COLOR_PEACH="#fe640b"
    export COLOR_YELLOW="#df8e1d"
    export COLOR_GREEN="#40a02b"
    export COLOR_TEAL="#179299"
    export COLOR_SKY="#04a5e5"
    export COLOR_SAPPHIRE="#209fb5"
    export COLOR_BLUE="#1e66f5"
    export COLOR_LAVENDER="#7287fd"
    export COLOR_TEXT="#4c4f69"
    export COLOR_SUBTEXT_1="#5c5f77"
    export COLOR_SUBTEXT_0="#6c6f85"
    export COLOR_OVERLAY_2="#7c7f93"
    export COLOR_OVERLAY_1="#8c8fa1"
    export COLOR_OVERLAY_0="#9ca0b0"
    export COLOR_SURFACE_2="#acb0be"
    export COLOR_SURFACE_1="#bcc0cc"
    export COLOR_SURFACE_0="#ccd0da"
    export COLOR_BASE="#eff1f5"
    export COLOR_MANTLE="#e6e9ef"
    export COLOR_CRUST="#dce0e8"
    ;;
    
  "frappe")
    # FrappCOLOR_é Palette
    export COLOR_ROSEWATER="#f2d5cf"
    export COLOR_FLAMINGO="#eebebe"
    export COLOR_PINK="#f4b8e4"
    export COLOR_MAUVE="#ca9ee6"
    export COLOR_RED="#e78284"
    export COLOR_MAROON="#ea999c"
    export COLOR_PEACH="#ef9f76"
    export COLOR_YELLOW="#e5c890"
    export COLOR_GREEN="#a6d189"
    export COLOR_TEAL="#81c8be"
    export COLOR_SKY="#99d1db"
    export COLOR_SAPPHIRE="#85c1dc"
    export COLOR_BLUE="#8caaee"
    export COLOR_LAVENDER="#babbf1"
    export COLOR_TEXT="#c6d0f5"
    export COLOR_SUBTEXT_1="#b5bfe2"
    export COLOR_SUBTEXT_0="#a5adce"
    export COLOR_OVERLAY_2="#949cbb"
    export COLOR_OVERLAY_1="#838ba7"
    export COLOR_OVERLAY_0="#737994"
    export COLOR_SURFACE_2="#626880"
    export COLOR_SURFACE_1="#51576d"
    export COLOR_SURFACE_0="#414559"
    export COLOR_BASE="#303446"
    export COLOR_MANTLE="#292c3c"
    export COLOR_CRUST="#232634"
    ;;
    
  "macchiato")
    # Macchiato Palette
    export COLOR_ROSEWATER="#f4dbd6"
    export COLOR_FLAMINGO="#f0c6c6"
    export COLOR_PINK="#f5bde6"
    export COLOR_MAUVE="#c6a0f6"
    export COLOR_RED="#ed8796"
    export COLOR_MAROON="#ee99a0"
    export COLOR_PEACH="#f5a97f"
    export COLOR_YELLOW="#eed49f"
    export COLOR_GREEN="#a6da95"
    export COLOR_TEAL="#8bd5ca"
    export COLOR_SKY="#91d7e3"
    export COLOR_SAPPHIRE="#7dc4e4"
    export COLOR_BLUE="#8aadf4"
    export COLOR_LAVENDER="#b7bdf8"
    export COLOR_TEXT="#cad3f5"
    export COLOR_SUBTEXT_1="#b8c0e0"
    export COLOR_SUBTEXT_0="#a5adcb"
    export COLOR_OVERLAY_2="#939ab7"
    export COLOR_OVERLAY_1="#8087a2"
    export COLOR_OVERLAY_0="#6e738d"
    export COLOR_SURFACE_2="#5b6078"
    export COLOR_SURFACE_1="#494d64"
    export COLOR_SURFACE_0="#363a4f"
    export COLOR_BASE="#24273a"
    export COLOR_MANTLE="#1e2030"
    export COLOR_CRUST="#181926"
    ;;
    
  "mocha")
    # Mocha
    export COLOR_ROSEWATER="#f5e0dc"
    export COLOR_FLAMINGO="#f2cdcd"
    export COLOR_PINK="#f5c2e7"
    export COLOR_MAUVE="#cba6f7"
    export COLOR_RED="#f38ba8"
    export COLOR_MAROON="#eba0ac"
    export COLOR_PEACH="#fab387"
    export COLOR_YELLOW="#f9e2af"
    export COLOR_GREEN="#a6e3a1"
    export COLOR_TEAL="#94e2d5"
    export COLOR_SKY="#89dceb"
    export COLOR_SAPPHIRE="#74c7ec"
    export COLOR_BLUE="#89b4fa"
    export COLOR_LAVENDER="#b4befe"
    export COLOR_TEXT="#cdd6f4"
    export COLOR_SUBTEXT_1="#bac2de"
    export COLOR_SUBTEXT_0="#a6adc8"
    export COLOR_OVERLAY_2="#9399b2"
    export COLOR_OVERLAY_1="#7f849c"
    export COLOR_OVERLAY_0="#6c7086"
    export COLOR_SURFACE_2="#585b70"
    export COLOR_SURFACE_1="#45475a"
    export COLOR_SURFACE_0="#313244"
    export COLOR_BASE="#1e1e2e"
    export COLOR_MANTLE="#181825"
    export COLOR_CRUST="#11111b"
    ;;

  *)
    ;;
esac
